version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ttDB
      POSTGRES_USER: sabo
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://sabo:example@db:5432/ttDB
      - POSTGRES_USER=sabo
      - POSTGRES_PASSWORD=example


